jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        architecture: x64
        java-package: jdk+fx
        java-version: 1.8
    - continue-on-error: true
      name: Build with jfxNative
      run: ./gradlew jfxNative --scan
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
